[package]
name = "workload"
version = "0.1.0"
authors = ["Boyd Johnson <johnson.boyd@gmail.com>"]

[dependencies]
clap = "2.29"
futures = "0.1"
tokio-core = "0.1"
tokio-timer = "0.1"
hyper = "0.11"
rand = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
